name: Run tests and apply terraform changes for current branch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        ./scripts/setup
    - name: Deploy production
      if: success() && contains(github.ref, 'master')
      env:
        ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_production }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_production }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_production }}
      run: |
        ./scripts/infra plan -var "gfw_api_token=${{ secrets.gfw_api_token_production }}" -var "slack_data_updates_hook=${{ secrets.slack_data_updates_hook }}" -var "rds_password=${{ secrets.rds_password_production }}" -var "rds_password_ro=${{ secrets.rds_password_ro_production }}"
        ./scripts/infra apply
    - name: Deploy staging
      if: success() && contains(github.ref, 'develop')
      env:
        ENV: staging
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_staging }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_staging }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_staging }}
      run: |
        ./scripts/infra plan -var "gfw_api_token=${{ secrets.gfw_api_token_staging }}" -var "slack_data_updates_hook=${{ secrets.slack_data_updates_hook }}" -var "rds_password=${{ secrets.rds_password_staging }}" -var "rds_password_ro=${{ secrets.rds_password_ro_staging }}"
        ./scripts/infra apply
    - name: Deploy dev
      if: success() && (! contains(github.ref, 'develop')) && (! contains(github.ref, 'master'))
      env:
        ENV: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_dev }}
      run: |
        ./scripts/infra plan -var "gfw_api_token=${{ secrets.gfw_api_token_staging }}" -var "slack_data_updates_hook=${{ secrets.slack_data_updates_hook }}" -var "rds_password=${{ secrets.rds_password_dev }}" -var "rds_password_ro=${{ secrets.rds_password_ro_dev }}"
        ./scripts/infra apply