name: Plan terraform changes for base branch

on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Plan production
      if: success() && contains(github.base_ref, 'master')
      env:
        ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_production }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_production }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_production }}
        GFW_API_TOKEN: ${{ secrets.gfw_api_token_production }}
        SLACK_DATA_UPDATES_HOOK: ${{ secrets.slack_data_updates_hook }}
        RDS_PASSWORD: ${{ secrets.rds_password_production }}
        RDS_PASSWORD_RO: ${{ secrets.rds_password_ro_production }}
      run: |
        ./scripts/infra plan \
        -var "gfw_api_token=${GFW_API_TOKEN}" \
        -var "slack_data_updates_hook=${SLACK_DATA_UPDATES_HOOK}" \
        -var "rds_password=${RDS_PASSWORD}" \
        -var "rds_password_ro=${RDS_PASSWORD_RO}"
    - name: Plan staging
      if: success() && contains(github.base_ref, 'develop')
      env:
        ENV: staging
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_staging }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_staging }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_staging }}
        GFW_API_TOKEN: ${{ secrets.gfw_api_token_staging }}
        SLACK_DATA_UPDATES_HOOK: ${{ secrets.slack_data_updates_hook }}
        RDS_PASSWORD: ${{ secrets.rds_password_staging }}
        RDS_PASSWORD_RO: ${{ secrets.rds_password_ro_staging }}
      run: |
        ./scripts/infra plan \
        -var "gfw_api_token=${GFW_API_TOKEN}" \
        -var "slack_data_updates_hook=${SLACK_DATA_UPDATES_HOOK}" \
        -var "rds_password=${RDS_PASSWORD}" \
        -var "rds_password_ro=${RDS_PASSWORD_RO}"
#    - name: Plan dev
#      if: success() && (! contains(github.base_ref, 'master')) && (! contains(github.base_ref, 'develop'))
#      env:
#        ENV: dev
#        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
#        AWS_DEFAULT_REGION: ${{ secrets.aws_region_dev }}
#        GFW_API_TOKEN: ${{ secrets.gfw_api_token_staging }}
#      run: ./scripts/infra plan ${{ github.base_ref }}
